apiVersion: apps/v1
kind: Deployment
metadata:
  name: razor-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: razor
  template:
    metadata:
      labels:
        app: razor
    spec:
      containers:
      - name: razor-app
        image: us-central1-docker.pkg.dev/machine-learning-416604/my-app-repo/razor-frontend:v3
        imagePullPolicy: Always  
        ports:
        - containerPort: 8080
        env:
        # 4. Updated the API Route
        - name: PYTHON_API_URL
          value: "http://python-api-internal/predict"
        # 5. Injecting the Key so the C# HttpClient can use it
        - name: API_KEY
          value: "dev-secret-key-123"
---
apiVersion: v1
kind: Service
metadata:
  name: razor-lb
spec:
  type: LoadBalancer
  selector:
    app: razor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080