using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using Xunit;
using System;
using System.Threading;

namespace EndToEndTests
{
    public class PredictionUITests : IDisposable
    {
        private readonly IWebDriver _driver;
        // In CI/CD, this will be passed as an environment variable pointing to the spun-up container
        private readonly string _appUrl = Environment.GetEnvironmentVariable("TEST_URL") ?? "http://localhost:5000/Prediction";

        public PredictionUITests()
        {
            var options = new ChromeOptions();
            options.AddArgument("--headless"); // Required for GitHub Actions
            options.AddArgument("--disable-gpu");
            options.AddArgument("--no-sandbox");
            
            _driver = new ChromeDriver(options);
            // Implicit wait to allow elements to load
            _driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5);
        }

        [Fact]
        public void RunPrediction_ValidInputs_ReturnsClass0OrClass1()
        {
            // 1. Navigate to the Razor Page
            _driver.Navigate().GoToUrl(_appUrl);

            // Verify we are on the right page
            Assert.Contains("Eviction Risk Assessment", _driver.Title ?? _driver.PageSource);

            // 2. Fill out the form
            // The 'name' attributes are automatically generated by the asp-for tag helpers
            _driver.FindElement(By.Name("TenantData.monthly_income")).SendKeys("5000");
            _driver.FindElement(By.Name("TenantData.monthly_debt")).SendKeys("1500");
            _driver.FindElement(By.Name("TenantData.credit_score")).SendKeys("720");
            _driver.FindElement(By.Name("TenantData.proposed_rent")).SendKeys("2000");
            _driver.FindElement(By.Name("TenantData.employment_tenure_months")).SendKeys("36");
            _driver.FindElement(By.Name("TenantData.years_at_prev_address")).SendKeys("4");
            _driver.FindElement(By.Name("TenantData.late_payment_count")).SendKeys("0");

            var evictionsDropdown = _driver.FindElement(By.Name("TenantData.prev_evictions"));
            var selectElement = new OpenQA.Selenium.Support.UI.SelectElement(evictionsDropdown);
            selectElement.SelectByValue("0");

            // 3. Submit the form
            _driver.FindElement(By.CssSelector("button[type='submit']")).Click();

            // 4. Wait for response and Assert
            // We sleep briefly to ensure the HTTP request completes and the DOM updates
            Thread.Sleep(2000); 
            
            var pageText = _driver.FindElement(By.TagName("body")).Text;

            // 5. Explicitly verify our strict mapping
            bool hasValidClass = pageText.Contains("Class 0") || pageText.Contains("Class 1");
            Assert.True(hasValidClass, "The prediction did not return a valid Class 0 or Class 1 result.");
        }

        public void Dispose()
        {
            // Cleanup after test finishes
            _driver.Quit();
            _driver.Dispose();
        }
    }
}