apiVersion: v1
kind: Service
metadata:
  name: real-estate-service
  labels:
    app: real-estate-app
spec:
  # Use 'LoadBalancer' to get a public IP, or 'ClusterIP' for internal-only
  type: LoadBalancer 
  selector:
    app: real-estate-app
  ports:
    - protocol: TCP
      port: 80        # The port the LoadBalancer listens on
      targetPort: 8080 # The port your Flask app/Gunicorn listens on